;;; -*-lexical-binding: t-*-

(use-package meow-tree-sitter
  :config
  (meow-tree-sitter-register-defaults))

(use-package meow
  :custom
  (meow-use-keypad-when-execute-kbd t)
  :init

  (defun meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

    (meow-motion-define-key
     '("q" . meow-quit)
     '("j" . meow-next)
     '("k" . meow-prev)
     '("C-h" . windmove-left)
     '("C-j" . windmove-down)
     '("C-k" . windmove-up)
     '("C-l" . windmove-right)
     '("/" . isearch-forward)
     '("?" . +lookup/documentation)
     '("<escape>" . ignore))
    (meow-leader-define-key
     ;; Use SPC (0-9) for digit arguments.
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument)
     '("`" . meow-last-buffer)
     (cons "/" meow-grep-global-map)
     '("?" . +lookup/documentation)
     (cons "a" meow-llm-global-map)
     (cons "b" meow-buffer-global-map)
     (cons "f" meow-file-global-map)
     (cons "h" help-map)
     (cons "i" meow-insert-global-map)
     (cons "j" meow-jump-global-map)
     (cons "n" meow-notes-global-map)
     (cons "p" project-prefix-map)
     (cons "t" meow-toggle-global-map)
     (cons "o" meow-special-global-map)
     (cons "v" meow-vc-global-map)
     (cons "s" meow-search-global-map)
     '("." . find-file))
    (meow-normal-define-key
     '("0" . meow-expand-0)
     '("9" . meow-expand-9)
     '("8" . meow-expand-8)
     '("7" . meow-expand-7)
     '("6" . meow-expand-6)
     '("5" . meow-expand-5)
     '("4" . meow-expand-4)
     '("3" . meow-expand-3)
     '("2" . meow-expand-2)
     '("1" . meow-expand-1)
     '("-" . negative-argument)
     '(":" . +meow/command)
     '(";" . meow-reverse)
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing)
     '("]" . meow-end-of-thing)
     '("}" . "M-}")
     '("{" . "M-{")
     '("a" . meow-append)
     '("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-kill)
     '("D" . meow-backward-delete)
     '("e" . meow-next-word)
     '("E" . meow-next-symbol)
     '("f" . meow-find)
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-insert)
     '("I" . meow-open-above)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("m" . meow-join)
     '("n" . meow-search)
     '("o" . meow-block)
     '("O" . meow-to-block)
     '("p" . meow-yank)
     '("P" . meow-yank-pop)
     '("q" . quoted-insert)
     '("Q" . meow-goto-line)
     '("r" . meow-replace)
     '("R" . meow-swap-grab)
     '("s" . +meow/select-for-mc-string)
     '("S" . +meow/select-for-mc-regex)
     '("t" . meow-till)
     '("u" . meow-undo)
     '("U" . undo-redo)
     '("v" . meow-visit)
     '("w" . meow-mark-word)
     '("W" . meow-mark-symbol)
     '("x" . meow-line)
     '("X" . meow-goto-line)
     '("y" . meow-save)
     '("Y" . meow-sync-grab)
     '("z" . meow-pop-selection)
     '("'" . repeat)
     '("\"" . +meow/surround-thing)
     '("<escape>" . keyboard-quit)
     '("/" . isearch-forward)
     (cons "|" meow-mc-global-map)
     '("?" . +lookup/documentation)
     (cons "M-?" meow-jump-global-map)
     '("C-r" . meow-redo)
     '("C-j" . windmove-down)
     '("C-k" . windmove-up)
     '("C-h" . windmove-left)
     '("C-l" . windmove-right))

    ;; kbd macro overrides
    (setq meow--kbd-kill-region "S-<delete>"
          meow--kbd-kill-ring-save "C-<insertchar>"
          meow-keypad-leader-dispatch nil)

    (setf (alist-get 'meow-kill meow-selection-command-fallback)
          'meow-delete)

    (setopt meow-mode-state-list (append meow-mode-state-list
                                         '((pdf-view-mode . motion)
                                           (calibredb-search-mode . motion)
                                           (ediff-mode . motion)
                                           (calibredb-show-mode . motion)
                                           (nov-mode . motion)
                                           (vterm-mode . insert)
                                           (shell-mode . insert)
                                           (eat-mode . insert)
                                           (shell-command-mode . motion)))))

  (defun +load-meow ()
    (require 'meow)
    (meow-setup)
    (meow-global-mode 1))
  :bind-keymap*
  (("C-x C-/" . meow-grep-global-map)
   ("C-x M-s" . meow-search-global-map))
  :bind*
  (("M-g <" . beginning-of-buffer)
   ("M-g >" . end-of-buffer)
   ("M-g f" . find-file-at-point)
   ("M-g W" . browse-url-at-point)
   ("M-<backspace>" . meow-backward-kill-symbol)
   ("C-o" . meow-pop-or-unpop-to-mark)
   ("C-v" . rectangle-mark-mode)
   :map meow-jump-global-map
   ("f" . find-file-at-point)
   ("W" . browse-url-at-point)
   :map meow-toggle-global-map
   ("c" . rainbow-mode)
   ("wm" . menu-bar-mode)
   ("wt" . tool-bar-mode)
   ("v" . visual-line-mode)
   :map help-map
   ("l" . load-library)
   :map meow-insert-global-map
   ("f" . insert-file)
   ("c" . insert-char)
   ("b" . insert-buffer))
  :hook
  (after-init-hook . +load-meow))

(provide 'init-meow)
